/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: h                                                     *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmh;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsh[] = {
  0x000000, 0xFFFFFF
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palh = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _ach[] = {
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ________, ________, ________, ________, ________,
  ________, ________, ________, ___XXXXX, X_______, ________, ________, ________,
  ________, ________, ________, _XXXXXXX, XXX_____, ________, ________, ________,
  ________, ________, ______XX, XXXXXXXX, XXXXX___, ________, ________, ________,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXX__, ________, ________, ________,
  ________, ________, __XXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________, ________,
  ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________,
  ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________, ________,
  ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, __XX____, ________, ________,
  ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ___XXXXX, XXXXXXXX, ________, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ___XXXXX, XXXXXX__, ________, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ___XXXXX, XXXX____, _______X, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, ___XXXXX, XX______, _______X, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, ____XXXX, X_______, _______X, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ____XXXX, ________, _______X, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ____XXXX, ________, ________, ____XXXX, XXXXXXXX, ________, ________,
  ________, ____XXX_, ________, ________, ______XX, XXXXXXXX, ________, ________,
  ________, ____XXX_, ________, ________, ________, XXXXXXXX, ________, ________,
  ________, ____XXX_, ________, ________, _______X, XXXXXXX_, ________, ________,
  ________, _____XX_, ________, ________, ____XXXX, XXXXXXX_, ________, ________,
  ________, _____XX_, ___XXXXX, XX____XX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, _____X__, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, _____X__, ________, XXXXXXXX, XXXXXX__, _XXXXXXX, ________, ________,
  ________, ________, ________, XXXXXXXX, XXXXX__X, XXXXXXXX, ________, ________,
  ________, ________, _____XXX, XXXXXX__, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ________, ___XXXXX, XXXX____, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, ________, __XXXXXX, XXXX____, _XXXXXXX, XXXXXXXX, X_______, ________,
  ________, ________, _______X, XXXX____, _XXXXXXX, XXXXXXXX, X_______, ________,
  ________, ____X___, _____XXX, XX______, _XXXXXXX, XXXXXXXX, XX______, ________,
  ________, ___XX___, ________, ________, _XXX____, _____XXX, XX______, ________,
  ________, ___X____, ________, ________, __XX____, _____XXX, XX______, ________,
  ________, ________, ________, ________, __XXX___, _____XXX, XX______, ________,
  ________, _____X__, ________, ________, __XXX___, _____XXX, XX______, ________,
  ________, _____X__, ________, ________, __XXX___, _____XXX, XX______, ________,
  ________, ________, ________, ________, _XXXXX__, ____XXXX, X_______, ________,
  ________, ________, ________, ____XXXX, XXXXXX__, ___XXXXX, X_______, ________,
  ________, ________, ________, ___XXXXX, XXXXXXX_, __XXXXXX, ________, ________,
  ________, ________, ________, ____XX_X, XXXXXXXX, _XXXXXXX, ________, ________,
  ________, ________, ________, ________, XXXXXXXX, XXXXXXX_, ________, ________,
  ________, ________, ___XX_X_, _______X, XXXXXXXX, XXXXXXX_, ________, ________,
  ________, ________, __XX_XXX, _______X, X_XXXXXX, XXXXXXX_, ________, ________,
  ________, ________, _____XXX, XX_____X, _XXXXXXX, XXXXXX__, ________, ________,
  ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________,
  ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________,
  ________, ________, ______XX, XXXX___X, XXXXXXXX, XXXXX___, ________, ________,
  ________, ________, _____XXX, X__XXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ________, ___XXXXX, ___XXXXX, XXXXXXXX, XXXX____, ________, ________,
  ________, ________, ____XXXX, X____XXX, XXXXXXXX, XXX_____, ________, ________,
  ________, ________, ____XXXX, XX_____X, XXXXXXXX, XXX_____, ________, ________,
  ________, ________, _____XXX, XX______, XXXXXXXX, XXX_____, ________, ________,
  ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  ________, _____X__, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, ____XXXX, XXXX____, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, __XXXXXX, XXXX____, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________,
  ________, XXXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________,
  ______XX, XXXXXXXX, XXX_____, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmh = {
  64, // xSize
  64, // ySize
  8, // BytesPerLine
  1, // BitsPerPixel
  _ach,  // Pointer to picture data (indices)
  &_Palh   // Pointer to palette
};

/*************************** End of file ****************************/
